ebdev:
    image: rjeschmi/easybuild-centos7:develop
    volumes:
        - ./export:/export/easybuild
        - ./eb:/software/easybuild-develop
        - ./spack:/software/spack
        - ./eb-module:/software/easybuild-develop/modulefiles
        - ./eb-easyblocks:/software/eb-easyblocks
        - ./eb-easyconfigs:/software/eb-easyconfigs
        - ./sources:/export/easybuild/sources
        - ./repos:/repos
        - ./scripts:/software/scripts
        - ./eb/config/config.cfg:/software/config/config.cfg
    user: root
    entrypoint: bash

mpeb:
    extends: ebdev
    image: rjeschmi/mpeb

ebdockerbrowser:
    extends: ebdev
    build: docker/ebdockerbrowser
