ebdev:
    image: rjeschmi/easybuild-centos7:develop
    volumes:
        - ./export:/export/easybuild
        - ./eb:/easybuild/easybuild-develop
        - ./eb-module:/easybuild/easybuild-develop/modulefiles
        - ./spack:/software/spack
        - ./eb-easyblocks:/software/eb-easyblocks
        - ./eb-easyconfigs:/software/eb-easyconfigs
        - /software/sources:/easybuild/sources
        - ./repos:/repos
        - ./scripts:/software/scripts
        - ./eb/config/config.cfg:/software/config/config.cfg
        - ./state/root_bash_history:/root/.bash_history
        - ./state/easybuild_bash_history:/home/easybuild/.bash_history
        - ./state/python_keyring:/home/easybuild/.local/share/python_keyring
    user: root
    entrypoint: bash
    working_dir: /easybuild/easybuild-develop/easybuild-framework
ebdevtest:
    extends: ebdev
    entrypoint: "/usr/bin/eb"
    volumes:
        - ./scripts/eb.wrapper:/usr/bin/eb
    user: easybuild
mpeb:
    extends: ebdev
    image: rjeschmi/mpeb

ebdockerbrowser:
    extends: ebdev
    build: docker/ebdockerbrowser
