easybuild:
    image: rjeschmi/easybuild-centos7
    volumes:
        - ./export:/export/easybuild
        - ./eb:/software/easybuild-develop
        - ./eb-module:/software/easybuild-develop/modulefiles
        - ./eb-easyblocks:/software/eb-easyblocks
        - ./eb-easyconfigs:/software/eb-easyconfigs
        - ./sources:/export/easybuild/sources
        - ./repos:/repos
        - ./scripts:/software/scripts
        - ./eb/config/config.cfg:/software/config/config.cfg
    user: root

easybuildfedora23:
    image: rjeschmi/easybuild-fedora23
    extends: easybuild

easybuild_build:
    extends: easybuild
    build: docker/centos7

BuildToolchain:
    extends: easybuild
    entrypoint: /software/scripts/easy_build

mpeb:
    extends: easybuild
    image: rjeschmi/mpeb

ebdockerbrowser:
    extends: easybuild
    build: docker/ebdockerbrowser
    user: easybuild
