ebdev:
    image: rjeschmi/easybuild-centos7:develop
    volumes:
        - ./export:/export/easybuild
        - ./eb:/easybuild/easybuild-develop
        - ./eb-module:/easybuild/easybuild-develop/modulefiles
        - ./spack:/software/spack
        - ./eb-easyblocks:/software/eb-easyblocks
        - ./eb-easyconfigs:/software/eb-easyconfigs
        - ./sources:/easybuild/sources
        - ./repos:/repos
        - ./scripts:/software/scripts
        - ./eb/config/config.cfg:/software/config/config.cfg
        - ./state/root_bash_history:/root/.bash_history
        - ./state/easybuild_bash_history:/home/easybuild/.bash_history
    user: root
    entrypoint: bash
    working_dir: /easybuild/easybuild-develop/easybuild-framework

mpeb:
    extends: ebdev
    image: rjeschmi/mpeb

ebdockerbrowser:
    extends: ebdev
    build: docker/ebdockerbrowser
