easybuild:
    image: rjeschmi/easybuild-centos6
    volumes:
        - ./export:/export/easybuild
        - ./eb:/software/easybuild-develop
        - ./eb-module:/software/easybuild-develop/modulefiles
        - ./eb-easyblocks:/software/eb-easyblocks
        - ./eb-easyconfigs:/software/eb-easyconfigs
    user: root
    volumes_from: 
        - EasybuildSources
        - EasybuildRepos


EasybuildGoolf1720:
    image: rjeschmi/easybuild-centos6
    volumes:
        - ./export:/export/easybuild
        - ./eb:/software/easybuild-develop
        - ./eb-module:/software/easybuild-develop/modulefiles
        - ./eb-easyblocks:/software/eb-easyblocks
        - ./eb-easyconfigs:/software/eb-easyconfigs
    user: root
    volumes_from: 
        - EasybuildSources
        - EasybuildRepos
    command: su -l -c 'eb FPM-1.3.3-Ruby-2.1.6.eb -r --prefix=/software/easybuild && ml load FPM/1.3.3-Ruby-2.1.6 && eb --experimental --package --sourcepath=/export/easybuild/sources --download-timeout=60 --prefix=/software/easybuild --packagepath=/repos/goolf-1.7.20 goolf-1.7.20 -dfr' - easybuild


EasybuildSources:
    image: centos:6
    volumes:
        - ./sources:/export/easybuild/sources
    command: echo

EasybuildRepos:
    image: centos:6
    volumes:
        - ./repos:/repos
    command: echo
