#!/bin/bash
tmux \
  new-session -s EasyBuild -n RootWindow \; \
  new-window -n EasyBuild \; \
  send-keys -t EasyBuild "su - easybuild" C-m \; \
  send-keys -t EasyBuild "ml load FPM" C-m \; \
  send-keys -t EasyBuild "ml av" C-m \; \
  selectw -t EasyBuild
