#!/usr/bin/env python
"""A script that is run within docker to handle building a specific repo"""

import os
import sys
import argparse
import glob
import subprocess
from subprocess import check_call, PIPE
from multiprocessing import Process

def module(command, arguments=[]):
    cmd = ['/software/Lmod/lmod/lmod/libexec/lmod', 'python'] + [command] + arguments
    try:
        process = subprocess.Popen(cmd, stdout=PIPE, stderr=PIPE)
        (stdout, stderr) = process.communicate()
        # print "stdout: %s stderr: %s" % (stdout, stderr)
        exec stdout #pylint: disable=W0122
    except Exception, err:
        print "Caught Exception err: %s in cmd: %s" % (err, cmd)
        sys.exit(1)

def update_sys_path():
    sys.path.extend(os.environ['PYTHONPATH'].split(os.pathsep))

def path_addto(destpath, srcpath):
    if os.getenv(destpath):
        os.environ[destpath] += os.pathsep + srcpath
    else:
        os.environ[destpath] = srcpath

    # print "environ: %s" % os.environ
def eb_main_call(*args, **kwargs):
    """A function that will be demoted and call eb_main_call"""
    demote()()
    args = kwargs.get('args', None)
    import easybuild.main as eb_main
    eb_main.main(args=args)

def eb_call(arguments, *args, **kwargs):
    opt_args = []
    eb_pkg = kwargs.get('eb_pkg', False)
    if eb_pkg:
        opt_args.extend([
            "--package",
        ])
    try:
        eb_kwargs = {'args': arguments}
        process = Process(target=eb_main_call, kwargs=eb_kwargs)
        process.start()
        process.join()
    except Exception, err:
        print "Caught Exception err: %s" % (err)
        sys.exit(1)

def demote():
    def set_ids():
        os.setgid(1000)
        os.setuid(1000)
    return set_ids

def call_build(args):
    """The build subcommand"""
    print "Building for toolchains: %s" % args.toolchains
    cmd = ["chown", "-R", "easybuild", "/software/easybuild"]
    path_addto("MODULEPATH", "/software/Lmod/lmod/lmod/modulefiles/Core")
    path_addto("MODULEPATH", "/software/easybuild-develop/modulefiles")
    path_addto("MODULEPATH", "/software/easybuild/modules/all")
    module("load", ["EasyBuild-develop"])
    update_sys_path()
    module("av")
    module("load", ["lmod"])
    if os.path.isfile("/repos/bootstrap/eb_bootstrap.tar.gz"):
        os.chdir("/software")
        cmd = ["tar", "xvzf", "/repos/bootstrap/eb_bootstrap.tar.gz"]
        output = subprocess.check_output(cmd)
        print "create_bootstrap: %s" % output

    elif not os.path.isdir("/software/easybuild/modules/all"):
        eb_call(["FPM-1.3.3-Ruby-2.1.6.eb", "-r", "--prefix=/software/easybuild"])
        os.chdir("/software")
        cmd = ["tar", "cvzf", "/repos/bootstrap/eb_bootstrap.tar.gz", "easybuild"]
        output = subprocess.check_output(cmd)
        print "bootstrap: %s" % output

    else:
        print "Found a preexisting software directory"

    for toolchain in args.toolchains:
        rpm_glob = "/repos/%s/*.rpm" % toolchain
        if glob.glob(rpm_glob):
            cmd = ["rpm", "-ivh", rpm_glob]
            check_call(cmd)
        eb_call(["FPM-1.3.3-Ruby-2.1.6.eb", "-r", "--prefix=/software/easybuild"])
        module("load", ["FPM/1.3.3-Ruby-2.1.6"])
        cmd = ["--package",
               "--sourcepath=/export/easybuild/sources --download-timeout=60",
               "--prefix=/software/easybuild",
               "--packagepath=/repos/%(repos)s %(repos)s.eb -dfr" % {'repos': toolchain}
              ]
        eb_call(cmd)

def main():
    """The main function, when run on the command-line"""
    parser = argparse.ArgumentParser()
    subparsers = parser.add_subparsers(help='sub-command help')
    parser_build = subparsers.add_parser('build', help='a command to build a toolchain')
    parser_build.add_argument('toolchains', nargs='+')
    parser_build.set_defaults(func=call_build)
    args = parser.parse_args()
    args.func(args)

if __name__ == '__main__':
    main()
